spring:
  application:
    name: OnlineStore
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:online_store}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:123456789}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true